{% set name = "flake8-pylint" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7741f9a63b05768fc4c641c7f6389bc33c91f9ed9bfd59c01540bbb7acc180e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.6
    - flake8
    - pylint

test:
  imports:
    - flake8_pylint
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/orsinium-labs/flake8-pylint
  summary: Flake8 plugin that runs PyLint.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
